baseURL = "/"
languageCode = "en-us"
title = "Alto"

disableKinds = ["RSS"]
enableRobotsTXT = true
disableAliases = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

[[menu.main]]
  name = "Components"
  weight = 5
  identifier = "components"
  url = "/components/"


[[menu.main]]
  name = "Utilities"
  weight = 10
  identifier = "utilities"
  url = "/utilities/"
