baseURL = "/alto/"
languageCode = "en-us"
title = "Alto"

# High level items

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Components"
  weight = 5
  identifier = "components"
  url = "/components/"


[[menu.main]]
  name = "Utilities"
  weight = 10
  identifier = "utilities"
  url = "/utilities/"
